### ISSUE TITLE
macOS 12.1 won't open authy

### ISSUE THREAD

**Issue by rlhennig** [momaek/authy#12]
I'm seeing this error:

> “authy” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.

I'm using Authy v0.1.7

**Comment by momaek** [comment]
Can you build it from source code by yourself ?

**Comment by paulknisely** [comment]
@rlhennig if after you receive that message, do you see an option to 'allow' in 'System Preferences > Security & Privacy' ?

**Comment by rlhennig** [comment]
Yes, that resolved the issue, thank you
