### ISSUE TITLE
Fuzz search doesn't contain all tokens

### ISSUE THREAD

**Issue by Cyberlane** [momaek/authy#18]
I have 25 tokens in Authy, but the `fuzz` search can only find 16 of them.

Is this perhaps a known problem?

**Comment by momaek** [comment]
What type of tokens? And make sure your tokens are backuped

**Comment by Cyberlane** [comment]
One example is I have 2x Outlook 365 accounts, both with their own domain names. One shows up in the fuzz search, the other does not. 

I have a number of others not showing up, but I'd say this one is a good example to work with. 

All my tokens are backed up and showing on both my mobile and desktop, but not with this CLI unfortunately. I'm not sure exactly how I could debug where the problem lies.

**Comment by zhouhailong** [comment]
Delet .authycache.json

**Comment by Cyberlane** [comment]
> Delet .authycache.json

That was it! Thank you!
