### ISSUE TITLE
Unable to use workflow, at keyword missing

### ISSUE THREAD

**Issue by LoSunny** [momaek/authy#3]
When I type the keyword `at`, it will refer to google search for some reason. Here is a video demonstrating the issue

https://cdn.discordapp.com/attachments/390433063500382220/834618420674297916/ScreenFlow.mp4

**Comment by momaek** [comment]
![image](https://user-images.githubusercontent.com/3843588/115685806-26b35280-a38b-11eb-9dac-d1ff3400188c.png)
Can you screenshot the config page in your alfredworkflow

**Comment by LoSunny** [comment]
![image](https://user-images.githubusercontent.com/25066078/115686157-801b8180-a38b-11eb-8a34-cf58df82e445.png)

**Comment by momaek** [comment]
![image](https://user-images.githubusercontent.com/3843588/115687364-abeb3700-a38c-11eb-8b73-0d43b6b0bbbb.png)
And Rerun `at`, If you got this error: 
```
[2021-04-22 17:04:14][STDERR: input.scriptfilter] zsh:1: command not found: authy
```
That means command `authy` is not in your $PATH or you don't config PATH to alfredworkflow. 

Check this: https://github.com/momaek/authy#q-dont-workdont-show-result

**Comment by LoSunny** [comment]
Oh yeah, that fixed the problem, at first I thought I can use the command in my `Terminal.app`, so it shouldn't be an issue with the command, but apparently it is and their `$PATH` is different
