### ISSUE TITLE
Cannot search tokens

### ISSUE THREAD

**Issue by janacm** [momaek/authy#4]
Hello,

This doesn't seem to be working on an M1 2021 MBP. I followed your steps, and got as far as having the "alfredworkflow" file created and imported in Alfred, but when I actually try to search my tokens I get nothing:

![image](https://user-images.githubusercontent.com/2055312/123179568-b2af2c80-d457-11eb-92bb-c9afbd1e221a.png)

![image](https://user-images.githubusercontent.com/2055312/123179533-990de500-d457-11eb-8a0b-2d6d8223724d.png)

I can even refresh my tokens successfully: 

![image](https://user-images.githubusercontent.com/2055312/123179505-8a273280-d457-11eb-98f0-a97f7f113888.png)

Also I'm not sure what happened during this step:

![image](https://user-images.githubusercontent.com/2055312/123179775-10437900-d458-11eb-93b1-d651e6a74922.png)

Does that look right to you? 

Thanks again for creating this workflow. Really excited to start using it!

**Comment by aviaryan** [comment]
For me, the CLI program searches but no result in the Alfred workflow.

**Comment by momaek** [comment]
Make sure that you have enabled ` Allow Multi-Device` in your Authy Application

**Comment by momaek** [comment]
And you can try this
```sh
authy fuzz git
```

**Comment by momaek** [comment]
Make sure `authy` cmd is in your $PATH and add this $PATH to Alfred workflow env

**Comment by janacm** [comment]
Thanks for the response. It worked after adding to my $path and running `chmod 777` on my `.authy.json` file.
