### ISSUE TITLE
Authy not updating new added accounts

### ISSUE THREAD

**Issue by abhilesh** [momaek/authy#6]
I've had authy up and running successfully for quite a while now and it works like a charm. However, I recently added a new account for nextcloud through the mobile app, but I cannot get the workflow to pick it up.

I've tried ```authy delpwd && authy refresh``` multiple times. It seems to run without any errors but doesn't seem to add the new accounts.

Any idea what might be happening here?

**Comment by momaek** [comment]
Do you enabled `Authenticator Backups` ?

![image](https://user-images.githubusercontent.com/3843588/126764263-b07ba80b-9ea8-4398-a736-63cba6feba09.png)

**Comment by abhilesh** [comment]
Yes, I do, also have multi-device sync enabled

**Comment by momaek** [comment]
After run `authy refresh`. Check your `$HOME/.authycache.json`. If exist the newest one

**Comment by abhilesh** [comment]
I had to delete that file and re-run ```authy``` from the command-line. After the refresh, the file contains the newer entries and things are working as expected. Thanks a lot for your help!

**Comment by AdamVyborny** [comment]
Same issue. Need to manually delete file and re-run `authy` from the command-line each time I add new account.
