### ISSUE TITLE
Fetch authenticator apps failed and empty .authy.json after connecting

### ISSUE THREAD

**Issue by notflip** [momaek/authy#9]
When I run `authy account` all works well, I receive a request on my phone and see the device id returned
however the `$HOME/.authy.json` file only contains `{}`

When I try to run `authy refresh` I get this error `token.go:101: Fetch authenticator apps failed {Message:Device not found AuthenticatorApps:[] Deleted:[] Success:false}`

**Comment by scholzie** [comment]
I had the same issue. I installed v0.1.4 and it works fine. I'm assuming it has something to do with the refactor done in version 0.1.5.

**Comment by momaek** [comment]
I've fixed this issue, Please check the latest version https://github.com/momaek/authy/releases
